# Generated by Django 4.2.4 on 2023-09-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_dateoption_time_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateoption',
            name='time_proposal',
            field=models.TimeField(),
        ),
    ]
